# Generated by Django 5.2.3 on 2025-06-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userverification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]